import React from "react";
import './Features.css';
import IndividualFeature from "./IndividualFeature";
import feature1 from '../assets/feature1.png'
import feature2 from '../assets/feature2.png'
import feature3 from '../assets/feature3.png'

const Features = () => {
    const data = [
        {
            img:feature1,
            heading:"Search",
            content:"Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen."
        },
        {
            img:feature2,
            heading:"Select",
            content:"Choose from thousands of options generated by the slogan maker that fit your needs."
        },
        {
            img:feature3,
            heading:"Stand out",
            content:"Congrats on your new slogan. It's time to win the world!"
        }
    ]
    return (
        <div className="features-container">
            <div className="ftrs">
                <IndividualFeature img={data[0].img} heading={data[0].heading} content={data[0].content} key={0} />
                <IndividualFeature img={data[1].img} heading={data[1].heading} content={data[1].content} key={1}/>
                <IndividualFeature img={data[2].img} heading={data[2].heading} content={data[2].content} key={2}/>
            </div>
        </div>
    )
}

export default Features;